- name: PLAY1
  hosts: local
  connection: local #Managing it's own node, No need of credentials
  tasks:
  - name: PLAY1 and TASK1
    ansible.builtin.debug:
      msg: "Hello from PLAY1 and Task1"

  - name: PLAY2 and Task1
    ansibkle.builtin.debug:
      msg: "Hello from PLAY2 and Task1"    