- name: variables
  hosts: local
  connection: local
  vars: #play level variables, global variables
    COURSE: "DevOps with AWS"
    DURATION: 120HRS
    TRAINER: Shiva
  tasks:
  - name: print variables
    vars: # Task level variables / Local variables, accessible only within the tasks. Tasks variables can override play level variables.
      COURSE: Ansible
    ansible.builtin.debug:
    msg: " Course is {{ COURSE }}, Duration is {{ DURATION }}, Trainer is {{ TRAINER }} "

  tasks:
  - name: print variables
    ansible.builtin.debug:
    msg: " Course is {{ COURSE }}, Duration is {{ DURATION }}, Trainer is {{ TRAINER }} "
 