- name: variables from files
  hosts: local
  connection: local
  vars_prompt:
  - name: COURSE
    prompt: please enter course name
    # By default prompt is confidential, if we specify (private: false) then it is not confidential
  - name: DURATION
    prompt: please enter course duration
  - name: TRAINER
    prompt: please enter Trainer name   
  tasks:
  - name: print course details
    ansible.builtin.debug:
      msg: "Course name is {{ COURSE }}, Duration is {{ DURATION }}, Trainer is {{ TRAINER }}"