- name: variables from inventory
  hosts: web
  tasks:
  - name: print course details
    ansible.builtin.debug:
      msg: "Course name is {{ COURSE }}, Duration is {{ DURATION }}, Trainer is {{ TRAINER }}" 