- name: variables
  hosts: local
  connection: local
  # vars:
  #   GREET: "play level variable"
  # vars_files:
  # - vars.yaml
  # vars_prompt:
  # - name: GREET
  #   prompt: enter the value of prompt level
  #   private: false
  tasks:
  - name: print variable
    # vars:
    #   GREET: task level variable
    ansible.builtin.debug:
      msg: "Hello from {{ GREET }}"