- name: filters
  hosts: local
  connection: local
  tasks: 
  - name: handle undefined variable
    ansible.builtin.debug:
      msg: " Hello {{ person | default('ganesh') }}"

  - name: convert string to list
    vars:
      fruits: "apple, banana, orange" #string
    ansible.builtin.debug:
      msg: " Fruits are: {{ fruits | split(',') }}"

  - name: convert map into list
    vars:
      course:
        name: Ansible
        duration: 10 hrs
        trainer: shiva
    ansible.builtin.debug:
      msg: "Course information: {{ course | dict2items }}"

  - name: convert list into map
    vars: 
      course:
      - {'key': 'name', 'value': 'Ansible'}
      - {'key': 'duration', 'value': '10 hrs'}
      - {'key': 'trainer', 'value': 'shiva'}
    ansible.builtin.debug:
     msg: " Course information: {{ course | items2dict }}" 

  - name: convert upper to lower
    vars:
      name: Teja Vardhan Reddy K
    ansible.builtin.debug:
      msg: "{{ name | lower }}"

  - name: convert lower to upper
    vars:
      name: teja vardhan reddy k
    ansible.builtin.debug:
      msg: "{{ name | upper }}"

  - name: print minimum and maximum numbers
    vars:
      numbers: [ 24, 47, 19, 4543, 2 ]
    ansible.builtin.debug:
      msg: "Max number is {{ numbers | max }} and Min number is {{ numbers | min }}"

  - name: check whether the ip address is valid or not 
    vars:
      ip: "2563.245.264.1"
    ansible.builtin.debug:
        msg: "{{ ip | ansible.utils.ipaddr }}" 
