- name: filters
  hosts: local
  connection: local
  tasks: 
  - name: handle undefined variable
    ansible.builtin.debug:
      msg: " Hello {{ person | default('ganesh') }}"

  - name: convert string to list
    vars:
      fruits: "apple, banana, orange" #string
    ansible.builtin.debug:
      msg: " Fruits are: {{ fruits | split(',') }}"

  - name: convert map into list
    vars:
      course:
        name: Ansible
        duration: 10 hrs
        trainer: shiva
    ansible.builtin.debug:
      msg: "Course information: {{ course | dict2items }}"

  - name: convert list into map
    vars: 
      course:
      - {'key': 'name', 'value': 'Ansible'},
      - {'key': 'duration', 'value': '10 hrs'},
      - {'key': 'trainer', 'value': 'shiva'}
    ansible.builtin.debug:
     msg: " Course information: {{ course | items2dict }}" 