- name: filters
  hosts: local
  connection: local
  tasks: 
  - name: handle undefined variable
    ansible.builtin.debug:
      msg: " Hello {{ person | default(ganesh) }}"

  - name: convert string to list
    vars:
      fruits: "apple, banana, orange" #string
    ansible.builtin.debug:
      msg: " Fruits are: {{ fruits | split(',') }}"
     